baseURL = 'https://corteisblog.netlify.app/'
languageCode = 'pt-br'
title = 'Casa Nerd'
theme = 'github-style'

[params]
  author = "Corteis"
  description = "'Li em algum lugar que o mundo se muda bit a bit'"
  github = "corteisjr"
  linkedin = "arcenio-corteisjr"
  instagram = "corteis_junior"
  email = "corteisjunior@gmail.com"
  url = "http://corteisjunior.netlify.com/"
  keywords = "blog, tutorial, designer, programador"
  rss = false
  lastmod = true
  userStatusEmoji = "😀"
  favicon = "/images/github.png"
  location = "Moçambique"