baseURL = 'https://casanerd.netlify.app/'
languageCode = 'pt-br'
title = 'Casa Nerd'
theme = 'github-style'

[params]
  author = "Corteis"
  description = "Estranho, apaixonado por tecnólogia, que literalmente não sabe se encaixar na sociedade."
  github = "https://github.com/corteisjr"
  linkedin = "https://www.linkedin.com/in/arcenio-corteisjr/"
  instagram = "https://www.instagram.com/corteis_junior/"
  email = "corteisjunior@gmail.com"
  url = "http://corteisjunior.netlify.com/"
  keywords = "blog, tutorial, designer, programador"
  rss = false
  lastmod = true
  userStatusEmoji = "😀"
  favicon = "/images/github.png"
  location = "Moçambique"